//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinanceManager.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfirmationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfirmationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalFinanceManager.App_GlobalResources.ConfirmationMessages", typeof(ConfirmationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this account?.
        /// </summary>
        public static string AccountConfirmationDeletion {
            get {
                return ResourceManager.GetString("AccountConfirmationDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this ATM withdraw?.
        /// </summary>
        public static string AtmWithdrawConfirmationDeletion {
            get {
                return ResourceManager.GetString("AtmWithdrawConfirmationDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this bank?.
        /// </summary>
        public static string BankConfirmationDeletion {
            get {
                return ResourceManager.GetString("BankConfirmationDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this country?.
        /// </summary>
        public static string CountryConfirmationDeletion {
            get {
                return ResourceManager.GetString("CountryConfirmationDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this currency?.
        /// </summary>
        public static string CurrencyConfirmationDeletion {
            get {
                return ResourceManager.GetString("CurrencyConfirmationDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this expenditure?.
        /// </summary>
        public static string ExpenditureConfirmationDeletion {
            get {
                return ResourceManager.GetString("ExpenditureConfirmationDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this expenditure type?.
        /// </summary>
        public static string ExpenditureTypeConfirmationDeletion {
            get {
                return ResourceManager.GetString("ExpenditureTypeConfirmationDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this income?.
        /// </summary>
        public static string IncomeConfirmationDeletion {
            get {
                return ResourceManager.GetString("IncomeConfirmationDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this payment method?.
        /// </summary>
        public static string PaymentMethodConfirmationDeletion {
            get {
                return ResourceManager.GetString("PaymentMethodConfirmationDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this pension?.
        /// </summary>
        public static string PensionConfirmationDeletion {
            get {
                return ResourceManager.GetString("PensionConfirmationDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this periodic outcome?.
        /// </summary>
        public static string PeriodicOutcomeConfirmationDeletion {
            get {
                return ResourceManager.GetString("PeriodicOutcomeConfirmationDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this salary?.
        /// </summary>
        public static string SalaryConfirmationDeletion {
            get {
                return ResourceManager.GetString("SalaryConfirmationDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this saving?.
        /// </summary>
        public static string SavingConfirmationDeletion {
            get {
                return ResourceManager.GetString("SavingConfirmationDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this tax?.
        /// </summary>
        public static string TaxConfirmationDeletion {
            get {
                return ResourceManager.GetString("TaxConfirmationDeletion", resourceCulture);
            }
        }
    }
}
