//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisabledButtonTooltips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisabledButtonTooltips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DisabledButtonTooltips", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is used by at least one expenditure. Please delete the expenditures first..
        /// </summary>
        internal static string AccountCantBeDeleted {
            get {
                return ResourceManager.GetString("AccountCantBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ATM withdraw is used by at least one expenditure. Please move first the expenditures to another ATM withdraw..
        /// </summary>
        internal static string AtmWithdrawCantBeDeleted {
            get {
                return ResourceManager.GetString("AtmWithdrawCantBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ATM withdraw is used by at least one expenditure. Please move first the expenditures to another ATM withdraw..
        /// </summary>
        internal static string AtmWithdrawCantBeEdited {
            get {
                return ResourceManager.GetString("AtmWithdrawCantBeEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank is used by at least one account. Please delete the accounts first. .
        /// </summary>
        internal static string BankCantBeDeleted {
            get {
                return ResourceManager.GetString("BankCantBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country is used by at least one bank/salary/pension/tax. Please delete the banks/salaries/pensions/taxes first. .
        /// </summary>
        internal static string CountryCantBeDeleted {
            get {
                return ResourceManager.GetString("CountryCantBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is used by at least one account/salary/pension/tax. Please delete the accounts/salaries/pensions/taxes first..
        /// </summary>
        internal static string CurrencyCantBeDeleted {
            get {
                return ResourceManager.GetString("CurrencyCantBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expenditure type is used by at least one expenditure. Please delete the expenditures first..
        /// </summary>
        internal static string ExpenditureTypeCantBeDeleted {
            get {
                return ResourceManager.GetString("ExpenditureTypeCantBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment method is used by at least one expenditure. Please delete the expenditures first..
        /// </summary>
        internal static string PaymentMethodCantBeDeleted {
            get {
                return ResourceManager.GetString("PaymentMethodCantBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tax is used by at least one salary. Please delete the salaries first..
        /// </summary>
        internal static string TaxCantBeDeleted {
            get {
                return ResourceManager.GetString("TaxCantBeDeleted", resourceCulture);
            }
        }
    }
}
