//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinanceManager.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TitleNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TitleNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalFinanceManager.App_GlobalResources.TitleNames", typeof(TitleNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        internal static string AccountCreate {
            get {
                return ResourceManager.GetString("AccountCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an account.
        /// </summary>
        internal static string AccountDelete {
            get {
                return ResourceManager.GetString("AccountDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit an account.
        /// </summary>
        internal static string AccountEdit {
            get {
                return ResourceManager.GetString("AccountEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of accounts.
        /// </summary>
        internal static string AccountList {
            get {
                return ResourceManager.GetString("AccountList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage accounts.
        /// </summary>
        internal static string AccountPages {
            get {
                return ResourceManager.GetString("AccountPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an ATM withdraw.
        /// </summary>
        internal static string AtmWithdrawCreate {
            get {
                return ResourceManager.GetString("AtmWithdrawCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an ATM withdraw.
        /// </summary>
        internal static string AtmWithdrawDelete {
            get {
                return ResourceManager.GetString("AtmWithdrawDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit an ATM withdraw.
        /// </summary>
        internal static string AtmWithdrawEdit {
            get {
                return ResourceManager.GetString("AtmWithdrawEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of ATM withdraws.
        /// </summary>
        internal static string AtmWithdrawList {
            get {
                return ResourceManager.GetString("AtmWithdrawList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage ATM withdraws.
        /// </summary>
        internal static string AtmWithdrawPages {
            get {
                return ResourceManager.GetString("AtmWithdrawPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a bank.
        /// </summary>
        internal static string BankCreate {
            get {
                return ResourceManager.GetString("BankCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a bank.
        /// </summary>
        internal static string BankDelete {
            get {
                return ResourceManager.GetString("BankDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a bank.
        /// </summary>
        internal static string BankEdit {
            get {
                return ResourceManager.GetString("BankEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of banks.
        /// </summary>
        internal static string BankList {
            get {
                return ResourceManager.GetString("BankList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage banks.
        /// </summary>
        internal static string BankPages {
            get {
                return ResourceManager.GetString("BankPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a budget plan.
        /// </summary>
        internal static string BudgetPlanCreate {
            get {
                return ResourceManager.GetString("BudgetPlanCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a budget plan.
        /// </summary>
        internal static string BudgetPlanDelete {
            get {
                return ResourceManager.GetString("BudgetPlanDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a budget plan.
        /// </summary>
        internal static string BudgetPlanEdit {
            get {
                return ResourceManager.GetString("BudgetPlanEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of budget plans.
        /// </summary>
        internal static string BudgetPlanList {
            get {
                return ResourceManager.GetString("BudgetPlanList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage budget plans.
        /// </summary>
        internal static string BudgetPlanPages {
            get {
                return ResourceManager.GetString("BudgetPlanPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View a budget plan.
        /// </summary>
        internal static string BudgetPlanView {
            get {
                return ResourceManager.GetString("BudgetPlanView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a country.
        /// </summary>
        internal static string CountryCreate {
            get {
                return ResourceManager.GetString("CountryCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a country.
        /// </summary>
        internal static string CountryDelete {
            get {
                return ResourceManager.GetString("CountryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a country.
        /// </summary>
        internal static string CountryEdit {
            get {
                return ResourceManager.GetString("CountryEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of countries.
        /// </summary>
        internal static string CountryList {
            get {
                return ResourceManager.GetString("CountryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage countries.
        /// </summary>
        internal static string CountryPages {
            get {
                return ResourceManager.GetString("CountryPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a currency.
        /// </summary>
        internal static string CurrencyCreate {
            get {
                return ResourceManager.GetString("CurrencyCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a currency.
        /// </summary>
        internal static string CurrencyDelete {
            get {
                return ResourceManager.GetString("CurrencyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a currency.
        /// </summary>
        internal static string CurrencyEdit {
            get {
                return ResourceManager.GetString("CurrencyEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of currencies.
        /// </summary>
        internal static string CurrencyList {
            get {
                return ResourceManager.GetString("CurrencyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage currencies.
        /// </summary>
        internal static string CurrencyPages {
            get {
                return ResourceManager.GetString("CurrencyPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an expenditure type.
        /// </summary>
        internal static string ExpenditureTypeCreate {
            get {
                return ResourceManager.GetString("ExpenditureTypeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an expenditure type.
        /// </summary>
        internal static string ExpenditureTypeDelete {
            get {
                return ResourceManager.GetString("ExpenditureTypeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit an expenditure type.
        /// </summary>
        internal static string ExpenditureTypeEdit {
            get {
                return ResourceManager.GetString("ExpenditureTypeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of expenditure types.
        /// </summary>
        internal static string ExpenditureTypeList {
            get {
                return ResourceManager.GetString("ExpenditureTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage expenditure types.
        /// </summary>
        internal static string ExpenditureTypePages {
            get {
                return ResourceManager.GetString("ExpenditureTypePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an income.
        /// </summary>
        internal static string IncomeCreate {
            get {
                return ResourceManager.GetString("IncomeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an income.
        /// </summary>
        internal static string IncomeDelete {
            get {
                return ResourceManager.GetString("IncomeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit an income.
        /// </summary>
        internal static string IncomeEdit {
            get {
                return ResourceManager.GetString("IncomeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of incomes.
        /// </summary>
        internal static string IncomeList {
            get {
                return ResourceManager.GetString("IncomeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage incomes.
        /// </summary>
        internal static string IncomePages {
            get {
                return ResourceManager.GetString("IncomePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a payment method.
        /// </summary>
        internal static string PaymentMethodCreate {
            get {
                return ResourceManager.GetString("PaymentMethodCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a payment method.
        /// </summary>
        internal static string PaymentMethodDelete {
            get {
                return ResourceManager.GetString("PaymentMethodDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a payment method.
        /// </summary>
        internal static string PaymentMethodEdit {
            get {
                return ResourceManager.GetString("PaymentMethodEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of payment methods.
        /// </summary>
        internal static string PaymentMethodList {
            get {
                return ResourceManager.GetString("PaymentMethodList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage payment methods.
        /// </summary>
        internal static string PaymentMethodPages {
            get {
                return ResourceManager.GetString("PaymentMethodPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an outcome.
        /// </summary>
        internal static string PeriodicOutcomeCreate {
            get {
                return ResourceManager.GetString("PeriodicOutcomeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an outcome.
        /// </summary>
        internal static string PeriodicOutcomeDelete {
            get {
                return ResourceManager.GetString("PeriodicOutcomeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit an outcome.
        /// </summary>
        internal static string PeriodicOutcomeEdit {
            get {
                return ResourceManager.GetString("PeriodicOutcomeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of outcomes.
        /// </summary>
        internal static string PeriodicOutcomeList {
            get {
                return ResourceManager.GetString("PeriodicOutcomeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage outcomes.
        /// </summary>
        internal static string PeriodicOutcomePages {
            get {
                return ResourceManager.GetString("PeriodicOutcomePages", resourceCulture);
            }
        }
    }
}
