version: "3.8"

networks:
  local-network:
    name: local-network
    external: true

services:

  auth-db:
    build:
      context: ./setup/auth_db
      dockerfile: dockerfile
    environment:
      DB_SERVER_NAME: db-server
      DB_SERVER_PORT: 1433
      DB_SA_PASSWORD: VerySecret1234!
    container_name: auth-db
    networks:
      - local-network

  pwdsalt-secret:
    build:
      context: ./setup/pwdsalt_secret
      dockerfile: dockerfile
    environment:
      AWS_ENDPOINT: http://localstack:4566
      AWS_REGION: eu-west-2
    container_name: pwdsalt-secret
    networks:
      - local-network
