//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinanceManager.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TitleNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TitleNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalFinanceManager.App_GlobalResources.TitleNames", typeof(TitleNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string AccountCreate {
            get {
                return ResourceManager.GetString("AccountCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an account.
        /// </summary>
        public static string AccountDelete {
            get {
                return ResourceManager.GetString("AccountDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit an account.
        /// </summary>
        public static string AccountEdit {
            get {
                return ResourceManager.GetString("AccountEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of accounts.
        /// </summary>
        public static string AccountList {
            get {
                return ResourceManager.GetString("AccountList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage accounts.
        /// </summary>
        public static string AccountPages {
            get {
                return ResourceManager.GetString("AccountPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an ATM withdraw.
        /// </summary>
        public static string AtmWithdrawCreate {
            get {
                return ResourceManager.GetString("AtmWithdrawCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an ATM withdraw.
        /// </summary>
        public static string AtmWithdrawDelete {
            get {
                return ResourceManager.GetString("AtmWithdrawDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit an ATM withdraw.
        /// </summary>
        public static string AtmWithdrawEdit {
            get {
                return ResourceManager.GetString("AtmWithdrawEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of ATM withdraws.
        /// </summary>
        public static string AtmWithdrawList {
            get {
                return ResourceManager.GetString("AtmWithdrawList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage ATM withdraws.
        /// </summary>
        public static string AtmWithdrawPages {
            get {
                return ResourceManager.GetString("AtmWithdrawPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a bank.
        /// </summary>
        public static string BankCreate {
            get {
                return ResourceManager.GetString("BankCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a bank.
        /// </summary>
        public static string BankDelete {
            get {
                return ResourceManager.GetString("BankDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a bank.
        /// </summary>
        public static string BankEdit {
            get {
                return ResourceManager.GetString("BankEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of banks.
        /// </summary>
        public static string BankList {
            get {
                return ResourceManager.GetString("BankList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage banks.
        /// </summary>
        public static string BankPages {
            get {
                return ResourceManager.GetString("BankPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a budget plan.
        /// </summary>
        public static string BudgetPlanCreate {
            get {
                return ResourceManager.GetString("BudgetPlanCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Planned Dashboard.
        /// </summary>
        public static string BudgetPlanDashboardPages {
            get {
                return ResourceManager.GetString("BudgetPlanDashboardPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a budget plan.
        /// </summary>
        public static string BudgetPlanDelete {
            get {
                return ResourceManager.GetString("BudgetPlanDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a budget plan.
        /// </summary>
        public static string BudgetPlanEdit {
            get {
                return ResourceManager.GetString("BudgetPlanEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of budget plans.
        /// </summary>
        public static string BudgetPlanList {
            get {
                return ResourceManager.GetString("BudgetPlanList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage budget plans.
        /// </summary>
        public static string BudgetPlanPages {
            get {
                return ResourceManager.GetString("BudgetPlanPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View a budget plan.
        /// </summary>
        public static string BudgetPlanView {
            get {
                return ResourceManager.GetString("BudgetPlanView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a country.
        /// </summary>
        public static string CountryCreate {
            get {
                return ResourceManager.GetString("CountryCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a country.
        /// </summary>
        public static string CountryDelete {
            get {
                return ResourceManager.GetString("CountryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a country.
        /// </summary>
        public static string CountryEdit {
            get {
                return ResourceManager.GetString("CountryEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of countries.
        /// </summary>
        public static string CountryList {
            get {
                return ResourceManager.GetString("CountryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage countries.
        /// </summary>
        public static string CountryPages {
            get {
                return ResourceManager.GetString("CountryPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a currency.
        /// </summary>
        public static string CurrencyCreate {
            get {
                return ResourceManager.GetString("CurrencyCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a currency.
        /// </summary>
        public static string CurrencyDelete {
            get {
                return ResourceManager.GetString("CurrencyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a currency.
        /// </summary>
        public static string CurrencyEdit {
            get {
                return ResourceManager.GetString("CurrencyEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of currencies.
        /// </summary>
        public static string CurrencyList {
            get {
                return ResourceManager.GetString("CurrencyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage currencies.
        /// </summary>
        public static string CurrencyPages {
            get {
                return ResourceManager.GetString("CurrencyPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an expense.
        /// </summary>
        public static string ExpenditureCreate {
            get {
                return ResourceManager.GetString("ExpenditureCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an expense.
        /// </summary>
        public static string ExpenditureDelete {
            get {
                return ResourceManager.GetString("ExpenditureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit an expense.
        /// </summary>
        public static string ExpenditureEdit {
            get {
                return ResourceManager.GetString("ExpenditureEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Expenses using CSV file.
        /// </summary>
        public static string ExpenditureImport {
            get {
                return ResourceManager.GetString("ExpenditureImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of expenses.
        /// </summary>
        public static string ExpenditureList {
            get {
                return ResourceManager.GetString("ExpenditureList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage expenses.
        /// </summary>
        public static string ExpenditurePages {
            get {
                return ResourceManager.GetString("ExpenditurePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenditure Split Dashboard.
        /// </summary>
        public static string ExpenditureSplitDashboardPages {
            get {
                return ResourceManager.GetString("ExpenditureSplitDashboardPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an expenditure type.
        /// </summary>
        public static string ExpenditureTypeCreate {
            get {
                return ResourceManager.GetString("ExpenditureTypeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an expenditure type.
        /// </summary>
        public static string ExpenditureTypeDelete {
            get {
                return ResourceManager.GetString("ExpenditureTypeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit an expenditure type.
        /// </summary>
        public static string ExpenditureTypeEdit {
            get {
                return ResourceManager.GetString("ExpenditureTypeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of expenditure types.
        /// </summary>
        public static string ExpenditureTypeList {
            get {
                return ResourceManager.GetString("ExpenditureTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage expenditure types.
        /// </summary>
        public static string ExpenditureTypePages {
            get {
                return ResourceManager.GetString("ExpenditureTypePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an income.
        /// </summary>
        public static string IncomeCreate {
            get {
                return ResourceManager.GetString("IncomeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an income.
        /// </summary>
        public static string IncomeDelete {
            get {
                return ResourceManager.GetString("IncomeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit an income.
        /// </summary>
        public static string IncomeEdit {
            get {
                return ResourceManager.GetString("IncomeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of incomes.
        /// </summary>
        public static string IncomeList {
            get {
                return ResourceManager.GetString("IncomeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage incomes.
        /// </summary>
        public static string IncomePages {
            get {
                return ResourceManager.GetString("IncomePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginPages {
            get {
                return ResourceManager.GetString("LoginPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement Import.
        /// </summary>
        public static string MovementImport {
            get {
                return ResourceManager.GetString("MovementImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a CSV file.
        /// </summary>
        public static string MovementImportUploadCsv {
            get {
                return ResourceManager.GetString("MovementImportUploadCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a payment method.
        /// </summary>
        public static string PaymentMethodCreate {
            get {
                return ResourceManager.GetString("PaymentMethodCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a payment method.
        /// </summary>
        public static string PaymentMethodDelete {
            get {
                return ResourceManager.GetString("PaymentMethodDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a payment method.
        /// </summary>
        public static string PaymentMethodEdit {
            get {
                return ResourceManager.GetString("PaymentMethodEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of payment methods.
        /// </summary>
        public static string PaymentMethodList {
            get {
                return ResourceManager.GetString("PaymentMethodList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage payment methods.
        /// </summary>
        public static string PaymentMethodPages {
            get {
                return ResourceManager.GetString("PaymentMethodPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a pension.
        /// </summary>
        public static string PensionCreate {
            get {
                return ResourceManager.GetString("PensionCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a pension.
        /// </summary>
        public static string PensionDelete {
            get {
                return ResourceManager.GetString("PensionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a pension.
        /// </summary>
        public static string PensionEdit {
            get {
                return ResourceManager.GetString("PensionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of pensions.
        /// </summary>
        public static string PensionList {
            get {
                return ResourceManager.GetString("PensionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage pensions.
        /// </summary>
        public static string PensionPages {
            get {
                return ResourceManager.GetString("PensionPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an outcome.
        /// </summary>
        public static string PeriodicOutcomeCreate {
            get {
                return ResourceManager.GetString("PeriodicOutcomeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an outcome.
        /// </summary>
        public static string PeriodicOutcomeDelete {
            get {
                return ResourceManager.GetString("PeriodicOutcomeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit an outcome.
        /// </summary>
        public static string PeriodicOutcomeEdit {
            get {
                return ResourceManager.GetString("PeriodicOutcomeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of outcomes.
        /// </summary>
        public static string PeriodicOutcomeList {
            get {
                return ResourceManager.GetString("PeriodicOutcomeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage outcomes.
        /// </summary>
        public static string PeriodicOutcomePages {
            get {
                return ResourceManager.GetString("PeriodicOutcomePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a salary.
        /// </summary>
        public static string SalaryCreate {
            get {
                return ResourceManager.GetString("SalaryCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a salary.
        /// </summary>
        public static string SalaryDelete {
            get {
                return ResourceManager.GetString("SalaryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a salary.
        /// </summary>
        public static string SalaryEdit {
            get {
                return ResourceManager.GetString("SalaryEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of salaries.
        /// </summary>
        public static string SalaryList {
            get {
                return ResourceManager.GetString("SalaryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage salaries.
        /// </summary>
        public static string SalaryPages {
            get {
                return ResourceManager.GetString("SalaryPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a saving.
        /// </summary>
        public static string SavingCreate {
            get {
                return ResourceManager.GetString("SavingCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a saving.
        /// </summary>
        public static string SavingDelete {
            get {
                return ResourceManager.GetString("SavingDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a saving.
        /// </summary>
        public static string SavingEdit {
            get {
                return ResourceManager.GetString("SavingEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of saving.
        /// </summary>
        public static string SavingList {
            get {
                return ResourceManager.GetString("SavingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage savings.
        /// </summary>
        public static string SavingPages {
            get {
                return ResourceManager.GetString("SavingPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a tax.
        /// </summary>
        public static string TaxCreate {
            get {
                return ResourceManager.GetString("TaxCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a tax.
        /// </summary>
        public static string TaxDelete {
            get {
                return ResourceManager.GetString("TaxDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a tax.
        /// </summary>
        public static string TaxEdit {
            get {
                return ResourceManager.GetString("TaxEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of taxes.
        /// </summary>
        public static string TaxList {
            get {
                return ResourceManager.GetString("TaxList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage taxes.
        /// </summary>
        public static string TaxPages {
            get {
                return ResourceManager.GetString("TaxPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of tax types.
        /// </summary>
        public static string TaxTypeList {
            get {
                return ResourceManager.GetString("TaxTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage tax types.
        /// </summary>
        public static string TaxTypePages {
            get {
                return ResourceManager.GetString("TaxTypePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create user profile.
        /// </summary>
        public static string UserProfileCreate {
            get {
                return ResourceManager.GetString("UserProfileCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user profile.
        /// </summary>
        public static string UserProfileEdit {
            get {
                return ResourceManager.GetString("UserProfileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage user profile.
        /// </summary>
        public static string UserProfilePages {
            get {
                return ResourceManager.GetString("UserProfilePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View user profile.
        /// </summary>
        public static string UserProfileView {
            get {
                return ResourceManager.GetString("UserProfileView", resourceCulture);
            }
        }
    }
}
