version: "3.8"

networks:
  local-network:
    name: local-network
    external: true

services:

  # Simulating a centralized SQL Server instance
  db-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: db-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=VerySecret1234!
      - MSSQL_ENABLE_HADR=0
      - MSSQL_AGENT_ENABLED=false
      - MSSQL_MEMORY_LIMIT_MB=4000
    ports:
      - "1433:1433"
    networks:
      - local-network

  # Simulating a logging system
  seq:
    container_name: seq
    image: datalust/seq:2022.1
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "80:80"
    networks:
      - local-network

  # Simulating AWS cloud 
  localstack:
    container_name: localstack
    build:
      dockerfile: Dockerfile
      context: ./PFM.Infra/localstack
    environment:
      - SERVICES=ssm
      - DEBUG=${DEBUG-}
      - AWS_DEFAULT_REGION=eu-west-2
      - DEFAULT_REGION=eu-west-2
      - HOSTNAME=localstack
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
      - "4510:4510"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - local-network

  # Simulating Eventstore
  eventstore:
    image: eventstore/eventstore:21.10.8-buster-slim
    container_name: eventstore
    environment:
      EVENTSTORE_INSECURE: True
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: True
      EVENTSTORE_RUN_PROJECTIONS: All
    ports:
      - "2112:2112"
      - "2113:2113"
    networks:
      - local-network
