version: "3.8"

networks:
  local-network:
    name: local-network
    external: true

services:

  db-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: db-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=VerySecret1234!
      - MSSQL_ENABLE_HADR=0
      - MSSQL_AGENT_ENABLED=false
      - MSSQL_MEMORY_LIMIT_MB=4000
    ports:
      - "1433:1433"
    networks:
      - local-network
