version: 2
updates:
  - package-ecosystem: "nuget" 
    directories: "/*/" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" 
    directories: "/*/" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions" 
    directory: "/" 
    schedule:
      interval: "weekly"
