version: 2
updates:
  - package-ecosystem: "nuget" 
    directories: 
      - "/*/" 
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "FluentAssertions"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker" 
    directories:
      - "/*/" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions" 
    directory: "/" 
    schedule:
      interval: "weekly"
