networks:
  local-network:
    name: local-network
    external: true

services:

  pfm-website-iac:
    build:
      context: ./setup/iac
      dockerfile: Dockerfile
    profiles: ["dev", "prod"]
    environment:
      AWS_ACCESS_KEY_ID: XX
      AWS_SECRET_ACCESS_KEY: XX
      AWS_ENDPOINT: http://localstack:4566
      AWS_REGION: eu-west-2
    container_name: pfm-website-iac
    networks:
      - local-network

  pfm-api:
    build:
      context: ../PFM.Api
      dockerfile: Dockerfile
      args:
        - GH_PKG_TOKEN_ARG=${GH_PKG_TOKEN}
    profiles: ["dev", "prod"]
    environment:
      ASPNETCORE_URLS: https://+:4431
      ASPNETCORE_ENVIRONMENT: Development
      OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889 # (logs via seq)
      APP_OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889 # OTEL defaults
      APP_ConnectionStrings__PFMConnection: Server=db-server,1433;Database=PFM_MAIN_DB;User Id=PFM_API_SVC;Password=Helloworld123!;TrustServerCertificate=True
      APP_ConnectionStrings__EventStoreConnection: esdb://eventstore:2113?tls=false
      APP_Auth__Authority: http://keycloak:8080/realms/pfm
      APP_Auth__ValidateIssuer: false
      APP_BankApi__EndpointUrl: https://pfm-bank-api:50001
      APP_DataSettings__DbConnection: Server=db-server,1433;Database=PFM_MVT_AGGR_DB;User Id=PFM_API_SVC;Password=Helloworld123!;TrustServerCertificate=True
    container_name: pfm-api
    ports:
      - "4431:4431"
    networks:
      - local-network
  
  pfm-bank-updater:
    build:
      context: ../PFM.BankAccountUpdater
      dockerfile: Dockerfile
      args:
        - GH_PKG_TOKEN_ARG=${GH_PKG_TOKEN}
    profiles: ["dev", "prod"]
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889 # (logs via seq)
      APP_OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889 # OTEL defaults
      APP_ConnectionStrings__EventStoreConnection: esdb://eventstore:2113?tls=false
      APP_AuthApi__EndpointUrl: http://keycloak:8080/realms/pfm/protocol/openid-connect/token/
      APP_BankApi__EndpointUrl: https://pfm-bank-api:50001
    container_name: pfm-bank-updater
    networks:
      - local-network

  pfm-mvt-aggregator:
    build:
      context: ../PFM.MovementAggregator
      dockerfile: Dockerfile
      args:
        - GH_PKG_TOKEN_ARG=${GH_PKG_TOKEN}
    profiles: ["dev", "prod"]
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889 # (logs via seq)
      APP_OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889 # OTEL defaults
      APP_ConnectionStrings__EventStoreConnection: esdb://eventstore:2113?tls=false
      APP_AuthApi__EndpointUrl: http://keycloak:8080/realms/pfm/protocol/openid-connect/token/
      APP_ApplicationSettings__DbConnection: Server=db-server,1433;Database=PFM_MVT_AGGR_DB;User Id=PFM_MVT_AGGR_SVC;Password=Helloworld123!;TrustServerCertificate=True
    container_name: pfm-mvt-aggregator
    networks:
      - local-network

  pfm-website:
    build:
      context: ../PFM.Website.Reboot
      dockerfile: Dockerfile
      args:
        - GH_PKG_TOKEN_ARG=${GH_PKG_TOKEN}
    container_name: pfm-website
    profiles: ["prod"]
    environment:
      ASPNETCORE_URLS: https://+:7143
      ASPNETCORE_ENVIRONMENT: Development
      OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889 # (logs via seq)
      APP_OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889 # OTEL defaults
      APP_AuthOptions__Authority: http://keycloak:8080/realms/pfm
      APP_UsePfmApi: true
      APP_PfmApi__EndpointUrl: https://pfm-api:4431/
    ports:
      - "7143:7143"
    networks:
      - local-network