version: "3.8"

networks:
  local-network:
    name: local-network
    external: true

services:

  pfm-website-iac:
    build:
      context: ./setup/iac
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: XX
      AWS_SECRET_ACCESS_KEY: XX
      AWS_ENDPOINT: http://localstack:4566
      AWS_REGION: eu-west-2
    container_name: pfm-website-iac
    networks:
      - local-network

  pfm-api:
    build:
      context: ../PFM.Api
      dockerfile: Dockerfile
      args:
        - GH_PKG_TOKEN_ARG=${GH_PKG_TOKEN}
    environment:
      ASPNETCORE_URLS: https://+:4431
      ASPNETCORE_ENVIRONMENT: Development
      APP_Serilog__WriteTo__1__Args__serverUrl: http://seq:5341
      APP_ConnectionStrings__PFMConnection: Server=db-server,1433;Database=PFM_MAIN_DB;User Id=PFM_API_SVC;Password=Helloworld123!;TrustServerCertificate=True
      APP_ConnectionStrings__EventStoreConnection: esdb://eventstore:2113?tls=false
      APP_Auth__Authority: http://keycloak:8080/realms/pfm
      APP_Auth__ValidateIssuer: false
      APP_BankApi__EndpointUrl: https://pfm-bank-api:50001
    container_name: pfm-api
    ports:
      - "4431:4431"
    networks:
      - local-network