//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinanceManager.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalFinanceManager.Models.Resources.DisplayNames", typeof(DisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string AccountBank {
            get {
                return ResourceManager.GetString("AccountBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string AccountCurrency {
            get {
                return ResourceManager.GetString("AccountCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Balance.
        /// </summary>
        internal static string AccountCurrentBalance {
            get {
                return ResourceManager.GetString("AccountCurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Balance.
        /// </summary>
        internal static string AccountInitialBalance {
            get {
                return ResourceManager.GetString("AccountInitialBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving account?.
        /// </summary>
        internal static string AccountIsSavingAccount {
            get {
                return ResourceManager.GetString("AccountIsSavingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Amount.
        /// </summary>
        internal static string AtmWithdrawCurrentAmount {
            get {
                return ResourceManager.GetString("AtmWithdrawCurrentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Withdraw.
        /// </summary>
        internal static string AtmWithdrawDateExpenditure {
            get {
                return ResourceManager.GetString("AtmWithdrawDateExpenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string AtmWithdrawDescription {
            get {
                return ResourceManager.GetString("AtmWithdrawDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Debited.
        /// </summary>
        internal static string AtmWithdrawHasBeenAlreadyDebited {
            get {
                return ResourceManager.GetString("AtmWithdrawHasBeenAlreadyDebited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Amount.
        /// </summary>
        internal static string AtmWithdrawInitialAmount {
            get {
                return ResourceManager.GetString("AtmWithdrawInitialAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        internal static string BankBranchAddressLine1 {
            get {
                return ResourceManager.GetString("BankBranchAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        internal static string BankBranchAddressLine2 {
            get {
                return ResourceManager.GetString("BankBranchAddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string BankBranchCity {
            get {
                return ResourceManager.GetString("BankBranchCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string BankBranchName {
            get {
                return ResourceManager.GetString("BankBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string BankBranchPhoneNumber {
            get {
                return ResourceManager.GetString("BankBranchPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code.
        /// </summary>
        internal static string BankBranchPostCode {
            get {
                return ResourceManager.GetString("BankBranchPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string BankCountry {
            get {
                return ResourceManager.GetString("BankCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Branch.
        /// </summary>
        internal static string BankFavoriteBranch {
            get {
                return ResourceManager.GetString("BankFavoriteBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string BankGeneralEnquiryPhoneNumber {
            get {
                return ResourceManager.GetString("BankGeneralEnquiryPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string BankIconPath {
            get {
                return ResourceManager.GetString("BankIconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string BankIconPathPreview {
            get {
                return ResourceManager.GetString("BankIconPathPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload an icon.
        /// </summary>
        internal static string BankUploadImage {
            get {
                return ResourceManager.GetString("BankUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string BankWebsite {
            get {
                return ResourceManager.GetString("BankWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Month Value.
        /// </summary>
        internal static string BudgetPlanAverageMonthValue {
            get {
                return ResourceManager.GetString("BudgetPlanAverageMonthValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string BudgetPlanEndDate {
            get {
                return ResourceManager.GetString("BudgetPlanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Value.
        /// </summary>
        internal static string BudgetPlanExpectedValue {
            get {
                return ResourceManager.GetString("BudgetPlanExpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenditure Type.
        /// </summary>
        internal static string BudgetPlanExpenditureType {
            get {
                return ResourceManager.GetString("BudgetPlanExpenditureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string BudgetPlanName {
            get {
                return ResourceManager.GetString("BudgetPlanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Month Value.
        /// </summary>
        internal static string BudgetPlanPreviousMonthValue {
            get {
                return ResourceManager.GetString("BudgetPlanPreviousMonthValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string BudgetPlanStartDate {
            get {
                return ResourceManager.GetString("BudgetPlanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CurrencyName {
            get {
                return ResourceManager.GetString("CurrencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string CurrencySymbol {
            get {
                return ResourceManager.GetString("CurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM Withdraw.
        /// </summary>
        internal static string ExpenditureAtmWithdraw {
            get {
                return ResourceManager.GetString("ExpenditureAtmWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ExpenditureDateExpenditure {
            get {
                return ResourceManager.GetString("ExpenditureDateExpenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ExpenditureDescription {
            get {
                return ResourceManager.GetString("ExpenditureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Debited.
        /// </summary>
        internal static string ExpenditureHasBeenAlreadyDebited {
            get {
                return ResourceManager.GetString("ExpenditureHasBeenAlreadyDebited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        internal static string ExpenditurePaymentMethod {
            get {
                return ResourceManager.GetString("ExpenditurePaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Account.
        /// </summary>
        internal static string ExpenditureTargetInternalAccount {
            get {
                return ResourceManager.GetString("ExpenditureTargetInternalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenditure Type.
        /// </summary>
        internal static string ExpenditureTypeExpenditure {
            get {
                return ResourceManager.GetString("ExpenditureTypeExpenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph Color.
        /// </summary>
        internal static string ExpenditureTypeGraphColor {
            get {
                return ResourceManager.GetString("ExpenditureTypeGraphColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ExpenditureTypeName {
            get {
                return ResourceManager.GetString("ExpenditureTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show On Dashboard.
        /// </summary>
        internal static string ExpenditureTypeShowOnDashboard {
            get {
                return ResourceManager.GetString("ExpenditureTypeShowOnDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string IncomeAccount {
            get {
                return ResourceManager.GetString("IncomeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string IncomeCost {
            get {
                return ResourceManager.GetString("IncomeCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Income.
        /// </summary>
        internal static string IncomeDateIncome {
            get {
                return ResourceManager.GetString("IncomeDateIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string IncomeDescription {
            get {
                return ResourceManager.GetString("IncomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string IncomeEndDate {
            get {
                return ResourceManager.GetString("IncomeEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string IncomeFrequency {
            get {
                return ResourceManager.GetString("IncomeFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string IncomeIsEnabled {
            get {
                return ResourceManager.GetString("IncomeIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string IncomeStartDate {
            get {
                return ResourceManager.GetString("IncomeStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM Withdraw Option.
        /// </summary>
        internal static string PaymentMethodHasAtmWithdrawOption {
            get {
                return ResourceManager.GetString("PaymentMethodHasAtmWithdrawOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Debited Option.
        /// </summary>
        internal static string PaymentMethodHasBeenAlreadyDebitedOption {
            get {
                return ResourceManager.GetString("PaymentMethodHasBeenAlreadyDebitedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PaymentMethodName {
            get {
                return ResourceManager.GetString("PaymentMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Contribution (%).
        /// </summary>
        internal static string PensionCompanyContributionPercentage {
            get {
                return ResourceManager.GetString("PensionCompanyContributionPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Contribution (%).
        /// </summary>
        internal static string PensionContributionPercentage {
            get {
                return ResourceManager.GetString("PensionContributionPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string PensionCountry {
            get {
                return ResourceManager.GetString("PensionCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string PensionCurrency {
            get {
                return ResourceManager.GetString("PensionCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Pot.
        /// </summary>
        internal static string PensionCurrentPot {
            get {
                return ResourceManager.GetString("PensionCurrentPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string PensionDescription {
            get {
                return ResourceManager.GetString("PensionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string PensionEndDate {
            get {
                return ResourceManager.GetString("PensionEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string PensionId {
            get {
                return ResourceManager.GetString("PensionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Interest (%).
        /// </summary>
        internal static string PensionInterest {
            get {
                return ResourceManager.GetString("PensionInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string PensionStartDate {
            get {
                return ResourceManager.GetString("PensionStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string PensionWebsite {
            get {
                return ResourceManager.GetString("PensionWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string PeriodicOutcomeAccount {
            get {
                return ResourceManager.GetString("PeriodicOutcomeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string PeriodicOutcomeCost {
            get {
                return ResourceManager.GetString("PeriodicOutcomeCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string PeriodicOutcomeDescription {
            get {
                return ResourceManager.GetString("PeriodicOutcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string PeriodicOutcomeEndDate {
            get {
                return ResourceManager.GetString("PeriodicOutcomeEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string PeriodicOutcomeFrequency {
            get {
                return ResourceManager.GetString("PeriodicOutcomeFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string PeriodicOutcomeIsEnabled {
            get {
                return ResourceManager.GetString("PeriodicOutcomeIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string PeriodicOutcomeStartDate {
            get {
                return ResourceManager.GetString("PeriodicOutcomeStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenditure Type.
        /// </summary>
        internal static string PeriodicOutcomeTypeExpenditure {
            get {
                return ResourceManager.GetString("PeriodicOutcomeTypeExpenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string SalaryCountry {
            get {
                return ResourceManager.GetString("SalaryCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string SalaryCurrency {
            get {
                return ResourceManager.GetString("SalaryCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Deductions.
        /// </summary>
        internal static string SalaryDeductions {
            get {
                return ResourceManager.GetString("SalaryDeductions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string SalaryDescription {
            get {
                return ResourceManager.GetString("SalaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string SalaryEndDate {
            get {
                return ResourceManager.GetString("SalaryEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Gross Pay.
        /// </summary>
        internal static string SalaryMonthlyGrossPay {
            get {
                return ResourceManager.GetString("SalaryMonthlyGrossPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Net Pay.
        /// </summary>
        internal static string SalaryMonthlyNetPay {
            get {
                return ResourceManager.GetString("SalaryMonthlyNetPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string SalaryStartDate {
            get {
                return ResourceManager.GetString("SalaryStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string SalaryTax {
            get {
                return ResourceManager.GetString("SalaryTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly Salary.
        /// </summary>
        internal static string SalaryYearlySalary {
            get {
                return ResourceManager.GetString("SalaryYearlySalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string SavingAmount {
            get {
                return ResourceManager.GetString("SavingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string SavingDateSaving {
            get {
                return ResourceManager.GetString("SavingDateSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string SavingDescription {
            get {
                return ResourceManager.GetString("SavingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Account.
        /// </summary>
        internal static string SavingTargetInternalAccount {
            get {
                return ResourceManager.GetString("SavingTargetInternalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code / Reference.
        /// </summary>
        internal static string TaxCode {
            get {
                return ResourceManager.GetString("TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string TaxCountry {
            get {
                return ResourceManager.GetString("TaxCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string TaxCurrency {
            get {
                return ResourceManager.GetString("TaxCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TaxDescription {
            get {
                return ResourceManager.GetString("TaxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string TaxEndDate {
            get {
                return ResourceManager.GetString("TaxEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequence.
        /// </summary>
        internal static string TaxFrequence {
            get {
                return ResourceManager.GetString("TaxFrequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequence Option.
        /// </summary>
        internal static string TaxFrequenceOption {
            get {
                return ResourceManager.GetString("TaxFrequenceOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string TaxId {
            get {
                return ResourceManager.GetString("TaxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string TaxStartDate {
            get {
                return ResourceManager.GetString("TaxStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Type.
        /// </summary>
        internal static string TaxType {
            get {
                return ResourceManager.GetString("TaxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string UserProfileFirstName {
            get {
                return ResourceManager.GetString("UserProfileFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string UserProfileLastName {
            get {
                return ResourceManager.GetString("UserProfileLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Wages.
        /// </summary>
        internal static string UserProfileSourceWages {
            get {
                return ResourceManager.GetString("UserProfileSourceWages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly Wages.
        /// </summary>
        internal static string UserProfileYearlyWages {
            get {
                return ResourceManager.GetString("UserProfileYearlyWages", resourceCulture);
            }
        }
    }
}
