//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinanceManager.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalFinanceManager.Models.Resources.DisplayNames", typeof(DisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Amount.
        /// </summary>
        internal static string AtmWithdrawCurrentAmount {
            get {
                return ResourceManager.GetString("AtmWithdrawCurrentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Withdraw.
        /// </summary>
        internal static string AtmWithdrawDateExpenditure {
            get {
                return ResourceManager.GetString("AtmWithdrawDateExpenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string AtmWithdrawDescription {
            get {
                return ResourceManager.GetString("AtmWithdrawDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Debited.
        /// </summary>
        internal static string AtmWithdrawHasBeenAlreadyDebited {
            get {
                return ResourceManager.GetString("AtmWithdrawHasBeenAlreadyDebited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Amount.
        /// </summary>
        internal static string AtmWithdrawInitialAmount {
            get {
                return ResourceManager.GetString("AtmWithdrawInitialAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string BankCountry {
            get {
                return ResourceManager.GetString("BankCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string BankIconPath {
            get {
                return ResourceManager.GetString("BankIconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string BankIconPathPreview {
            get {
                return ResourceManager.GetString("BankIconPathPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload an icon.
        /// </summary>
        internal static string BankUploadImage {
            get {
                return ResourceManager.GetString("BankUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CurrencyName {
            get {
                return ResourceManager.GetString("CurrencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string CurrencySymbol {
            get {
                return ResourceManager.GetString("CurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM Withdraw.
        /// </summary>
        internal static string ExpenditureAtmWithdraw {
            get {
                return ResourceManager.GetString("ExpenditureAtmWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ExpenditureDateExpenditure {
            get {
                return ResourceManager.GetString("ExpenditureDateExpenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ExpenditureDescription {
            get {
                return ResourceManager.GetString("ExpenditureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Debited.
        /// </summary>
        internal static string ExpenditureHasBeenAlreadyDebited {
            get {
                return ResourceManager.GetString("ExpenditureHasBeenAlreadyDebited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        internal static string ExpenditurePaymentMethod {
            get {
                return ResourceManager.GetString("ExpenditurePaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Account.
        /// </summary>
        internal static string ExpenditureTargetInternalAccount {
            get {
                return ResourceManager.GetString("ExpenditureTargetInternalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenditure Type.
        /// </summary>
        internal static string ExpenditureTypeExpenditure {
            get {
                return ResourceManager.GetString("ExpenditureTypeExpenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph Color.
        /// </summary>
        internal static string ExpenditureTypeGraphColor {
            get {
                return ResourceManager.GetString("ExpenditureTypeGraphColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ExpenditureTypeName {
            get {
                return ResourceManager.GetString("ExpenditureTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show On Dashboard.
        /// </summary>
        internal static string ExpenditureTypeShowOnDashboard {
            get {
                return ResourceManager.GetString("ExpenditureTypeShowOnDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string IncomeAccount {
            get {
                return ResourceManager.GetString("IncomeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string IncomeCost {
            get {
                return ResourceManager.GetString("IncomeCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Income.
        /// </summary>
        internal static string IncomeDateIncome {
            get {
                return ResourceManager.GetString("IncomeDateIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string IncomeDescription {
            get {
                return ResourceManager.GetString("IncomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string IncomeEndDate {
            get {
                return ResourceManager.GetString("IncomeEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string IncomeFrequency {
            get {
                return ResourceManager.GetString("IncomeFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string IncomeIsEnabled {
            get {
                return ResourceManager.GetString("IncomeIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string IncomeStartDate {
            get {
                return ResourceManager.GetString("IncomeStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM Withdraw Option.
        /// </summary>
        internal static string PaymentMethodHasAtmWithdrawOption {
            get {
                return ResourceManager.GetString("PaymentMethodHasAtmWithdrawOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Debited Option.
        /// </summary>
        internal static string PaymentMethodHasBeenAlreadyDebitedOption {
            get {
                return ResourceManager.GetString("PaymentMethodHasBeenAlreadyDebitedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PaymentMethodName {
            get {
                return ResourceManager.GetString("PaymentMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string PeriodicOutcomeAccount {
            get {
                return ResourceManager.GetString("PeriodicOutcomeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string PeriodicOutcomeCost {
            get {
                return ResourceManager.GetString("PeriodicOutcomeCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string PeriodicOutcomeDescription {
            get {
                return ResourceManager.GetString("PeriodicOutcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string PeriodicOutcomeEndDate {
            get {
                return ResourceManager.GetString("PeriodicOutcomeEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string PeriodicOutcomeFrequency {
            get {
                return ResourceManager.GetString("PeriodicOutcomeFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string PeriodicOutcomeIsEnabled {
            get {
                return ResourceManager.GetString("PeriodicOutcomeIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string PeriodicOutcomeStartDate {
            get {
                return ResourceManager.GetString("PeriodicOutcomeStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenditure Type.
        /// </summary>
        internal static string PeriodicOutcomeTypeExpenditure {
            get {
                return ResourceManager.GetString("PeriodicOutcomeTypeExpenditure", resourceCulture);
            }
        }
    }
}
