v1alpha1.extension_repo(name='default', url='https://github.com/tilt-dev/tilt-extensions')
load('ext://logger', 'logger')

def run_docker_compose(config):
  logger.info("Load docker-compose " + config["description"])
  docker_compose(config["path"], profiles=["dev"], env_file="./PFM.Infra/configs/.env")
