version: "3.8"

networks:
  local-network:
    name: local-network
    external: true

services:

  evs-sub:
    build:
      context: ./setup/evs-sub
      dockerfile: dockerfile
    environment:
      EVS_API_URL: http://eventstore:2113
    container_name: evs-sub
    networks:
      - local-network

  # pfm-auth-bank-updater-creds:
  #   build:
  #     context: ./setup/pfm-auth-creds
  #     dockerfile: dockerfile
  #   environment:
  #     API_URL: http://pfm-auth-api:5000
  #   container_name: pfm-auth-bank-updater-creds
  #   networks:
  #     - local-network
