//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinanceManager.Core.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessExceptionMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessExceptionMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalFinanceManager.Core.Exceptions.BusinessExceptionMessage", typeof(BusinessExceptionMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate account name for the same bank. Choose another name..
        /// </summary>
        public static string AccountDuplicateName {
            get {
                return ResourceManager.GetString("AccountDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate bank name. Choose another name..
        /// </summary>
        public static string BankDuplicateName {
            get {
                return ResourceManager.GetString("BankDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate country name. Choose another name..
        /// </summary>
        public static string CountryDuplicateName {
            get {
                return ResourceManager.GetString("CountryDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate currency name. Choose another name..
        /// </summary>
        public static string CurrencyDuplicateName {
            get {
                return ResourceManager.GetString("CurrencyDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement is not allowed. The cost of the expenditure is more expensive than the available amount on the ATM withdraw current balance. Select another ATM Withdraw..
        /// </summary>
        public static string ExpenditureExceededAtmWithdrawBalance {
            get {
                return ResourceManager.GetString("ExpenditureExceededAtmWithdrawBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate expenditure type color. Choose another name..
        /// </summary>
        public static string ExpenditureTypeDuplicateGraphColor {
            get {
                return ResourceManager.GetString("ExpenditureTypeDuplicateGraphColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate expenditure type name. Choose another name..
        /// </summary>
        public static string ExpenditureTypeDuplicateName {
            get {
                return ResourceManager.GetString("ExpenditureTypeDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is empty..
        /// </summary>
        public static string FileUploadEmpty {
            get {
                return ResourceManager.GetString("FileUploadEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file has been selected. .
        /// </summary>
        public static string FileUploadHasNotBeenSelected {
            get {
                return ResourceManager.GetString("FileUploadHasNotBeenSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file should not exceed {0} bytes..
        /// </summary>
        public static string FileUploadMaxSize {
            get {
                return ResourceManager.GetString("FileUploadMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the same name already exists..
        /// </summary>
        public static string FileUploadSameName {
            get {
                return ResourceManager.GetString("FileUploadSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file extension {0} does not match the allowed extensions ({1})..
        /// </summary>
        public static string FileUploadWrongExtensions {
            get {
                return ResourceManager.GetString("FileUploadWrongExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate payment method name. Choose another name..
        /// </summary>
        public static string PaymentMethodDuplicateName {
            get {
                return ResourceManager.GetString("PaymentMethodDuplicateName", resourceCulture);
            }
        }
    }
}
