USE PFM_AUTH_DB
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'Users'))
BEGIN
	CREATE TABLE [dbo].[Users] (
		[Id] INT IDENTITY (1, 1) NOT NULL,
		[FirstName] NVARCHAR(256) NOT NULL,
		[LastName] NVARCHAR(256) NOT NULL,
		[Username] NVARCHAR(256) NOT NULL,
		[Password] varbinary(1024) NOT NULL
	);
END
GO

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'UserTokens'))
BEGIN
	CREATE TABLE [dbo].[UserTokens] (
		[Id] INT IDENTITY (1, 1) NOT NULL,
		[Username] NVARCHAR(256) NOT NULL,
		[Token] NVARCHAR(4000) NOT NULL
	);
END
GO
