version: "3.8"

networks:
  local-network:
    name: local-network
    external: true

services:

  evs-sub-mvt-aggregator:
    build:
      context: ./setup/evs-sub
      dockerfile: dockerfile
    environment:
      EVS_API_URL: http://eventstore:2113
    container_name: evs-sub-mvt-aggregator
    networks:
      - local-network
