version: "3.8"

networks:
  local-network:
    name: local-network
    external: true

services:

  evs-sub-mvt-aggregator:
    build:
      context: ./setup/evs-sub
      dockerfile: dockerfile
    profiles: ["dev", "prod"]
    environment:
      EVS_API_URL: http://eventstore:2113
    container_name: evs-sub-mvt-aggregator
    networks:
      - local-network

  mvt-aggregator-db:
    build:
      context: ./setup/db
      dockerfile: dockerfile
    profiles: ["dev", "prod"]
    environment:
      DB_SERVER_NAME: db-server
      DB_SERVER_PORT: 1433
      DB_SA_PASSWORD: VerySecret1234!
    container_name: mvt-aggregator-db
    networks:
      - local-network