version: "3.8"

networks:
  local-network:
    name: local-network
    external: true

services:

  bank-db:
    build:
      context: ./setup/db
      dockerfile: dockerfile
    environment:
      DB_SERVER_NAME: db-server
      DB_SERVER_PORT: 1433
      DB_SA_PASSWORD: VerySecret1234!
    container_name: bank-db
    networks:
      - local-network
