USE PFM_MAIN_DB
GO

-- Enumeration: TaxType

IF NOT EXISTS (SELECT * FROM [dbo].[TaxTypes] WHERE [Id] = 1)
BEGIN
    INSERT INTO [dbo].[TaxTypes]([Id], [Name], [Description]) VALUES(1, 'Local Tax', 'A tax assessed and levied by a local authority such as a county or municipality. A local tax is usually collected in the form of property taxes, and is used to fund a wide range of civic services from garbage collection to sewer maintenance. The amount of local taxes may vary widely from one jurisdiction to the next.')
END

IF NOT EXISTS (SELECT * FROM [dbo].[TaxTypes] WHERE [Id] = 2)
BEGIN
    INSERT INTO [dbo].[TaxTypes]([Id], [Name], [Description]) VALUES(2, 'Property Tax', 'Property tax is a tax assessed on real estate. The tax is usually based on the value of the property (including the land) you own and is often assessed by local or municipal governments.')
END

IF NOT EXISTS (SELECT * FROM [dbo].[TaxTypes] WHERE [Id] = 3)
BEGIN
    INSERT INTO [dbo].[TaxTypes]([Id], [Name], [Description]) VALUES(3, 'Income Tax', 'An income tax is a tax that governments impose on financial income generated by all entities within their jurisdiction. By law, businesses and individuals must file an income tax return every year to determine whether they owe any taxes or are eligible for a tax refund. Income tax is a key source of funds that the government uses to fund its activities and serve the public.')
END

-- Enumeration: PaymentMethod

IF NOT EXISTS (SELECT * FROM [dbo].[PaymentMethods] WHERE [Id] = 1)
BEGIN
    INSERT INTO [dbo].[PaymentMethods]([Id], [Name], [CssClass], [IconClass], [HasBeenAlreadyDebitedOption]) VALUES(1, 'CB', 'primary', 'fa fa-credit-card', 1)
END

IF NOT EXISTS (SELECT * FROM [dbo].[PaymentMethods] WHERE [Id] = 2)
BEGIN
    INSERT INTO [dbo].[PaymentMethods]([Id], [Name], [CssClass], [IconClass], [HasBeenAlreadyDebitedOption]) VALUES(2, 'Cash', 'info', 'fa fa-money', 0)
END

IF NOT EXISTS (SELECT * FROM [dbo].[PaymentMethods] WHERE [Id] = 3)
BEGIN
    INSERT INTO [dbo].[PaymentMethods]([Id], [Name], [CssClass], [IconClass], [HasBeenAlreadyDebitedOption]) VALUES(3, 'Direct Debit', 'success', 'fa fa-credit-card-alt', 0)
END

IF NOT EXISTS (SELECT * FROM [dbo].[PaymentMethods] WHERE [Id] = 4)
BEGIN
    INSERT INTO [dbo].[PaymentMethods]([Id], [Name], [CssClass], [IconClass], [HasBeenAlreadyDebitedOption]) VALUES(4, 'Transfer', 'warning', 'fa fa-external-link', 0)
END

IF NOT EXISTS (SELECT * FROM [dbo].[PaymentMethods] WHERE [Id] = 5)
BEGIN
    INSERT INTO [dbo].[PaymentMethods]([Id], [Name], [CssClass], [IconClass], [HasBeenAlreadyDebitedOption]) VALUES(5, 'Internal Transfer', 'danger', 'fa fa-refresh', 0)
END

-- Enumeration: FrequenceOption

IF NOT EXISTS (SELECT * FROM [dbo].[FrequenceOptions] WHERE [Id] = 1)
BEGIN
    INSERT INTO [dbo].[FrequenceOptions]([Id], [Name]) VALUES(1, 'Once')
END

IF NOT EXISTS (SELECT * FROM [dbo].[FrequenceOptions] WHERE [Id] = 2)
BEGIN
    INSERT INTO [dbo].[FrequenceOptions]([Id], [Name]) VALUES(2, 'Every X Months')
END

SET IDENTITY_INSERT [dbo].[Countries] ON
INSERT INTO [dbo].[Countries] (Id, Name) VALUES (1, 'United Kingdom')
INSERT INTO [dbo].[Countries] (Id, Name) VALUES (2, 'France')
INSERT INTO [dbo].[Countries] (Id, Name) VALUES (3, 'Germany')
INSERT INTO [dbo].[Countries] (Id, Name) VALUES (4, 'Spain')
INSERT INTO [dbo].[Countries] (Id, Name) VALUES (5, 'Italy')
SET IDENTITY_INSERT [dbo].[Countries] OFF
