version: "3.8"

networks:
  api-local-network:
    name: api-local-network
    external: true

services:

  main-db:
    build:
      context: ./infra/main_db_init
      dockerfile: dockerfile
    environment:
      DB_SERVER_NAME: db-server
      DB_SERVER_PORT: 1433
      DB_SA_PASSWORD: VerySecret1234!
    container_name: main-db
    networks:
      - api-local-network
