networks:
  local-network:
    name: local-network
    external: true

services:

  main-db:
    build:
      context: ./setup/main_db
      dockerfile: dockerfile
    profiles: ["dev", "prod"]
    environment:
      DB_SERVER_NAME: db-server
      DB_SERVER_PORT: 1433
      DB_SA_PASSWORD: VerySecret1234!
    container_name: main-db
    networks:
      - local-network

  pfm-bank-api:
    build:
      context: ../PFM.Bank.Api
      dockerfile: Dockerfile
      args:
        - GH_PKG_TOKEN_ARG=${GH_PKG_TOKEN}
    profiles: ["dev", "prod"]
    environment:
      ASPNETCORE_URLS: https://+:50001
      ASPNETCORE_ENVIRONMENT: Development
      APP_Serilog__WriteTo__1__Args__serverUrl: http://seq:5341
      APP_ConnectionStrings__PFMConnection: Server=db-server,1433;Database=PFM_BANK_DB;User Id=PFM_BANK_API_SVC;Password=Helloworld123!;TrustServerCertificate=True
      APP_ConnectionStrings__EventStoreConnection: esdb://eventstore:2113?tls=false
      APP_Auth__Authority: http://keycloak:8080/realms/pfm
      APP_Auth__ValidateIssuer: false
      AWS_ACCESS_KEY_ID: XX
      AWS_SECRET_ACCESS_KEY: XX
    container_name: pfm-bank-api
    ports:
      - "50001:50001"
    networks:
      - local-network

  iac-batch-movements:
    build:
      context: ./setup/iac-batch-movements
      dockerfile: Dockerfile
    profiles: ["dev"]
    environment:
      AWS_ACCESS_KEY_ID: XXX
      AWS_SECRET_ACCESS_KEY: XXX
      AWS_ENDPOINT: http://localstack:4566
      AWS_REGION: eu-west-2
    container_name: iac-batch-movements
    networks:
      - local-network