version: "3.8"

networks:
  local-network:
    name: local-network
    external: true

services:

  iac:
    build:
      context: ./setup/iac
      dockerfile: dockerfile
    profiles: ["demo"]
    environment:
      AWS_ACCESS_KEY_ID: XX
      AWS_SECRET_ACCESS_KEY: XX
      AWS_ENDPOINT: http://localstack:4566
      AWS_REGION: eu-west-2
    container_name: iac
    networks:
      - local-network
