name: Build & Publish PFM Common Libraries

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Create Git Release"]
    type:
      - complete

env:
  DOTNET_ENV: '2.1.x'
  WORKDIR: PFM.Api/
  GITHUB_ORG: 'JM89'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '6.x'
          includePrerelease: true
          
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Display GitVersion outputs (step output)
        run: |
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"

      - name: Log in to access GitHub Packages 
        run: dotnet nuget add source --username ${{ env.GITHUB_ORG }} --password ${{ secrets.GITHUB_TOKEN }} "https://nuget.pkg.github.com/${{ env.GITHUB_ORG }}/index.json" --name "${{ env.GITHUB_ORG }} - GitHub Packages" 

      - name: Setup .NET Core SDK ${{ env.DOTNET_ENV }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_ENV }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build API Contracts
        working-directory: ${{ env.WORKDIR }}/src/PFM.Api.Contracts
        run: dotnet build --configuration Release --no-restore

      - name: Pack API Contracts
        working-directory: ${{ env.WORKDIR }}/src/PFM.Api.Contracts
        run: dotnet pack --configuration Release /p:Version=${{ steps.gitversion.outputs.fullSemVer }}
      
      - name: Publish API Contracts
        working-directory: ${{ env.WORKDIR }}/src/PFM.Api.Contracts
        run: dotnet nuget push "bin/Release/PFM.Api.Contracts.${{ steps.gitversion.outputs.fullSemVer }}.nupkg" --api-key ${{ secrets.PAT_WRITE_PACKAGES }} --source "${{ env.GITHUB_ORG }} - GitHub Packages" 
      
