name: Build PFM Website

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  WORKDIR: PFM.Website/

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Setup Nuget
        uses: Nuget/setup-nuget@v1.0.2
      - name: Install dependencies
        run: nuget restore PersonalFinanceManager.sln
      - name: Build
        run: msbuild PersonalFinanceManager.sln
