name: Build and Tests PFM Auth Api

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  DOTNET_ENV: '6.0.x'
  WORKDIR: PFM.Auth.Api/

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ env.DOTNET_ENV }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_ENV }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx"
      - name: Test Reporter
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: .NET Tests 
          path: test/PFM.Authentication.Api.Tests/TestResults/test-results.trx
          reporter: 'dotnet-trx'