name: Build and Tests PFM Website

on:
  push:
    branches:
      - main
  #pull_request:
  workflow_dispatch:

env:
  WORKDIR: PFM.Website/
  GITHUB_ORG: JM89

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Setup Nuget
        uses: Nuget/setup-nuget@v1.2.0
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1.2
      - name: Log in to access GitHub Packages 
        run: nuget sources Add -Name "${{ env.GITHUB_ORG }} - GitHub Packages" -Source "https://nuget.pkg.github.com/${{ env.GITHUB_ORG }}/index.json" -UserName ${{ env.GITHUB_ORG }} -Password ${{ secrets.PAT_READ_PACKAGES }} 
      - name: Install dependencies
        run: nuget restore PersonalFinanceManager.sln
      - name: Build
        run: msbuild PersonalFinanceManager.sln /p:platform="Any CPU" /p:configuration="Release"
      - name: Run Tests
        run: vstest.console.exe test\PersonalFinanceManager.ApiContractTests\bin\Release\net6.0\PersonalFinanceManager.ApiContractTests.dll